import { componentLabels, defaultComponentProps } from "../store/useBuilderStore";

const STYLE_KEYS = [
  "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight",
  "margin", "marginTop", "marginRight", "marginBottom", "marginLeft",
  "padding", "paddingTop", "paddingRight", "paddingBottom", "paddingLeft",
  "backgroundColor", "color", "borderRadius", "border", "borderWidth",
  "borderColor", "borderStyle", "boxShadow", "opacity", "display",
  "flexDirection", "flexWrap", "justifyContent", "alignItems", "alignContent",
  "gap", "position", "top", "right", "bottom", "left", "zIndex",
  "fontSize", "fontWeight", "fontFamily", "lineHeight", "letterSpacing",
  "textAlign", "textDecoration", "textTransform",
  "overflow", "cursor", "transition",
];

export const STYLE_FIELDS = STYLE_KEYS;

export const styleFieldMeta = {
  width: { label: "Width", type: "unit" },
  height: { label: "Height", type: "unit" },
  minWidth: { label: "Min Width", type: "unit" },
  minHeight: { label: "Min Height", type: "unit" },
  maxWidth: { label: "Max Width", type: "unit" },
  maxHeight: { label: "Max Height", type: "unit" },
  margin: { label: "Margin", type: "unit" },
  padding: { label: "Padding", type: "unit" },
  marginTop: { label: "Margin Top", type: "unit" },
  marginRight: { label: "Margin Right", type: "unit" },
  marginBottom: { label: "Margin Bottom", type: "unit" },
  marginLeft: { label: "Margin Left", type: "unit" },
  paddingTop: { label: "Padding Top", type: "unit" },
  paddingRight: { label: "Padding Right", type: "unit" },
  paddingBottom: { label: "Padding Bottom", type: "unit" },
  paddingLeft: { label: "Padding Left", type: "unit" },
  backgroundColor: { label: "Background", type: "color" },
  color: { label: "Text Color", type: "color" },
  borderColor: { label: "Border Color", type: "color" },
  borderRadius: { label: "Border Radius", type: "unit" },
  borderWidth: { label: "Border Width", type: "unit" },
  borderStyle: { label: "Border Style", type: "select", options: ["none", "solid", "dashed", "dotted", "double"] },
  border: { label: "Border Shorthand", type: "text" },
  boxShadow: { label: "Shadow", type: "select", options: ["none", "0 1px 3px rgba(0,0,0,0.1)", "0 4px 6px rgba(0,0,0,0.1)", "0 10px 25px rgba(0,0,0,0.15)", "0 20px 40px rgba(0,0,0,0.2)"] },
  opacity: { label: "Opacity", type: "range", min: 0, max: 1, step: 0.05 },
  display: { label: "Display", type: "select", options: ["block", "flex", "grid", "inline-block", "inline", "none"] },
  flexDirection: { label: "Flex Direction", type: "select", options: ["row", "column", "row-reverse", "column-reverse"] },
  flexWrap: { label: "Flex Wrap", type: "select", options: ["nowrap", "wrap", "wrap-reverse"] },
  justifyContent: { label: "Justify Content", type: "select", options: ["flex-start", "center", "flex-end", "space-between", "space-around", "space-evenly"] },
  alignItems: { label: "Align Items", type: "select", options: ["stretch", "flex-start", "center", "flex-end", "baseline"] },
  gap: { label: "Gap", type: "unit" },
  position: { label: "Position", type: "select", options: ["static", "relative", "absolute", "fixed", "sticky"] },
  top: { label: "Top", type: "unit" },
  right: { label: "Right", type: "unit" },
  bottom: { label: "Bottom", type: "unit" },
  left: { label: "Left", type: "unit" },
  zIndex: { label: "Z-Index", type: "number" },
  fontSize: { label: "Font Size", type: "unit" },
  fontWeight: { label: "Font Weight", type: "select", options: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] },
  fontFamily: { label: "Font Family", type: "text" },
  lineHeight: { label: "Line Height", type: "text" },
  letterSpacing: { label: "Letter Spacing", type: "unit" },
  textAlign: { label: "Text Align", type: "select", options: ["left", "center", "right", "justify"] },
  textDecoration: { label: "Text Decoration", type: "select", options: ["none", "underline", "line-through", "overline"] },
  textTransform: { label: "Text Transform", type: "select", options: ["none", "uppercase", "lowercase", "capitalize"] },
  overflow: { label: "Overflow", type: "select", options: ["visible", "hidden", "scroll", "auto"] },
  cursor: { label: "Cursor", type: "select", options: ["default", "pointer", "text", "move", "grab", "not-allowed"] },
  transition: { label: "Transition", type: "text" },
};
